
package com.epam.jmp.dr.task17.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPWebServiceImplService", targetNamespace = "http://ws.soap.task17.dr.jmp.epam.com/", wsdlLocation = "http://localhost:9999/soapws?wsdl")
public class SOAPWebServiceImplService
    extends Service
{

    private final static URL SOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SOAPWEBSERVICEIMPLSERVICE_QNAME = new QName("http://ws.soap.task17.dr.jmp.epam.com/", "SOAPWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/soapws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SOAPWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SOAPWebServiceImplService() {
        super(__getWsdlLocation(), SOAPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SOAPWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SOAPWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SOAPWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SOAPWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPWebService
     */
    @WebEndpoint(name = "SOAPWebServiceImplPort")
    public SOAPWebService getSOAPWebServiceImplPort() {
        return super.getPort(new QName("http://ws.soap.task17.dr.jmp.epam.com/", "SOAPWebServiceImplPort"), SOAPWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPWebService
     */
    @WebEndpoint(name = "SOAPWebServiceImplPort")
    public SOAPWebService getSOAPWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.task17.dr.jmp.epam.com/", "SOAPWebServiceImplPort"), SOAPWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
